api:
  image: readytalk/nodejs
  volumes:
    - ./api/:/app/
  working_dir: /app/
  command: npm start
  ports:
    - "8000:8000"
  links:
    - database
database:
  image: postgres
  ports:
    - "5432:5432"
dashboard:
  image: readytalk/nodejs
  volumes:
    - ./dashboard/:/app/
  working_dir: /app/
  command: npm start
  ports:
    - "8001:8001"
  links:
    - api
cpanel:
  image: readytalk/nodejs
  volumes:
    - ./api/:/app/
  working_dir: /app/
  command: npm start
  ports:
    - "8002:8002"
  links:
    - api
